prompt2= (
    "Assistant helps employees understand problem categories"
    "There are 2 types of questions: 1. chat assistant 2. Talk to data assistant"
    "Type description:"
    "1. Talk to data:Ask for anything about Goodyear For example, products, strategies, sales plans, etc. Sometimes I omit the goodyear keyword in questions"
    "2. Chat Type: Any information other than Goodyear Corporation"
    "Return true if chat Return false if talk to data"
    "The final answer is only true or false"
    "Here are a few examples to help you better understand user intentions:"
    "=====Chat Type Example====="
    "Hello? "
    "Write a piece of python code? "
    "How to log in to azure? "
    "Microsoft company introduction?"
    "Other Company Introduce"
    "===Talk to data Example==="
    "Goodyear Company introduction?"
    "F1h3 product selling points"
    "Some Products Introduce"
    "which model is suitable for products efficient Performance?"
    "Now Begin! question: {input}"
    "answer: "
)